### ISSUE TITLE
Enable development builds for documentation

### ISSUE THREAD

**Issue by Zethson** [theislab/pertpy#62]
```
python:
    version: 3.8
    install:
        - method: pip
          path: .
        - requirements: docs/requirements.txt
```

in .readthedocs.yml
